language: javascript
sudo: required
services:
  - docker

before_install:
  - docker build -t filip123456/docker-react -f Dockerfile.dev .

#script:
#  - docker run filip123456/docker-react npm run test -- --coverage

deploy:
  edge: true 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-945134210508" 
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"
