sudo: required
services:
  - docker

before_install:
  - docker build -t Filipnoz8888/docker-react -f Dockerfile.dev .

script:
  - docker run Filipnoz/docker-react npm run test -- --coverage

deploy:
  edge: true 
  provider: elsticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-945134210508" 
  bucket_path: "docker"
  on:
    branch: master
